language: cpp
script:
  - miner/pow/travis-install-libsodium.sh
  - cd miner
  - cmake .
  - make
  - cd ..
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - libboost-all-dev
