language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      before_install: brew install openssl
      env: 
        - BUILD_TYPE=Debug
        - OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

    - os: osx
      osx_image: xcode9.3
      before_install: brew install openssl
      env: 
        - BUILD_TYPE=Release
        - OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
            - libssl-dev
      before_install:
        - eval "CC=gcc-7 && CXX=g++-7"
      env: BUILD_TYPE=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
            - libssl-dev
      before_install:
        - eval "CC=gcc-7 && CXX=g++-7"
      env: BUILD_TYPE=Release

script: 
  - if [ $BUILD_TYPE == "Debug" ]; then 
      cmake -DCMAKE_BUILD_TYPE=Debug .;
      make;
      ctest --verbose;
    elif [ $TRAVIS_EVENT_TYPE == "cron" ]; then
      cmake -DCMAKE_BUILD_TYPE=Release .;
      make;
    else
      echo Nothing to build...;
    fi

after_success: 
  - if [ $TRAVIS_EVENT_TYPE == "cron" ] && [ $BUILD_TYPE == "Release" ]; then 
      chmod +x ./deploy.sh;
      ./deploy.sh;
    fi

notifications:
  email:
    - big.romanov@gmail.com
