language: android
sudo: true

android:
  components:
    - tools
    - platform-tools

install:
  - echo y | sdkmanager "ndk-bundle"

before_install:
  - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
  - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
  - sudo git clone --depth=1 https://github.com/nesbox/boost_1_68-android.git /usr/local/boost_1_68-android
  - sudo git clone --depth=1 https://github.com/nesbox/Prebuilt-OpenSSL-Android.git /usr/local/Prebuilt-OpenSSL-Android

before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
  - export BOOST_ROOT_ANDROID=/usr/local/boost_1_68-android
  - export OPENSSL_ROOT_DIR_ANDROID=/usr/local/Prebuilt-OpenSSL-Android/Prebuilt
  - export PATH=$ANDROID_NDK_HOME:$PATH

script:
  - cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86 .
  - make -j4
