language: cpp
script:
  - miner/pow/travis-install-libsodium.sh
  - cd miner
  - cmake .
  - make
  - cd ..
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-7
      - cmake-data
      - cmake
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
