language: cpp
sudo: required
script:
  - miner/pow/travis-install-libsodium.sh
  - cd miner
  - cmake .
  - make
  - cd ..
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake-data
      - cmake
      - libboost-all-dev
env:
  - CXX=g++-7
