language: cpp

script:
  - cmake .
  - make
  - ctest --verbose test

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
      #before_install:
        #- eval "brew install boost"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
      before_install:
        - eval "CC=gcc-7 && CXX=g++-7"

notifications:
  email:
    - big.romanov@gmail.com

