language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      before_install: 
        - brew upgrade boost cmake
        - brew install qt5
        - export PATH=/usr/local/opt/qt/bin:$PATH
      env: 
        - BUILD_TYPE=Debug
        - OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make -j 4 && ctest --verbose

    - os: osx
      osx_image: xcode9.3
      before_install:
        - brew upgrade openssl boost cmake
        - sudo git clone https://github.com/nesbox/qt5-static-mac.git /usr/local/qt5-static
        - export PATH=~/qt5-static/bin:$PATH
      env: 
        - BUILD_TYPE=Release
        - OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
        - QT5_ROOT_DIR="/usr/local/qt5-static"
        - QML_IMPORT_PATH="/usr/local/qt5-static/qml"
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBEAM_LINK_TYPE=Static . && make -j 4 && ctest --verbose && cpack;
      after_success:
        - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then 
            chmod +x ./deploy.sh;
            ./deploy.sh;
          fi

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
            - libssl-dev
      before_install:
        - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
        - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
        - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
        - sudo apt-get update
        - sudo apt-get install qt510declarative qt510svg
        - eval "CC=gcc-7 && CXX=g++-7"
        - export PATH=/opt/qt510/bin:$PATH
      env: BUILD_TYPE=Debug
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE . && make -j 4 && ctest --verbose

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
            - libssl-dev
      before_install:
        - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
        - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
        - eval "CC=gcc-7 && CXX=g++-7"
        - git clone https://github.com/nesbox/qt5-static-linux.git ~/qt5-static
      env: 
        - QT5_ROOT_DIR="~/qt5-static"
        - QML_IMPORT_PATH="~/qt5-static/qml"
        - BUILD_TYPE=Release
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBEAM_LINK_TYPE=Static . && make -j 4 && ctest --verbose && cpack;
      after_success:
        - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then 
            chmod +x ./deploy.sh;
            ./deploy.sh;
          fi

notifications:
  email:
    - big.romanov@gmail.com
