language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      before_install:
        - brew upgrade openssl boost cmake
        - sudo git clone --depth=1 https://github.com/nesbox/qt5-static-mac.git /usr/local/qt5-static
        - export PATH=~/qt5-static/bin:$PATH
      env: 
        - BUILD_TYPE=Release
        - OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
        - QT5_ROOT_DIR="/usr/local/qt5-static"
        - QML_IMPORT_PATH="/usr/local/qt5-static/qml"
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBEAM_LINK_TYPE=Static . && make -j 4 && ctest --verbose && cpack;
      after_success:
        - chmod +x ./deploy.sh;
        - ./deploy.sh;

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
            - libssl-dev
      before_install:
        - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
        - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
        - eval "CC=gcc-7 && CXX=g++-7"
        - git clone --depth=1 https://github.com/nesbox/qt5-static-linux.git /home/travis/qt5-static
      env: 
        - QT5_ROOT_DIR="/home/travis/qt5-static"
        - QML_IMPORT_PATH="/home/travis/qt5-static/qml"
        - BUILD_TYPE=Release
      script:
        - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBEAM_LINK_TYPE=Static . && make -j 4 && ctest --verbose && cpack;
      after_success:
        - chmod +x ./deploy.sh;
        - ./deploy.sh;

notifications:
  email:
    - big.romanov@gmail.com
