language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      before_install: brew install openssl
      env: OPENSSL_ROOT_DIR="/usr/local/opt/openssl"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
            - libssl-dev
      before_install:
        - eval "CC=gcc-7 && CXX=g++-7"

notifications:
  email:
    - big.romanov@gmail.com

jobs:
  include:
    - stage: building...
      script: 
        - ctest --verbose

    # - stage: testing...
    #   script: 
    #     - ctest --verbose

    - stage: deploying...
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: beam/beam
        skip_cleanup: true
        on:
          tags: true