language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
	  before_script:
		- export PATH=$PATH:/usr/local/opt/qt/bin
      before_install: 
        - brew upgrade openssl boost cmake
        - brew install qt5
      env: 
        - BUILD_TYPE=Debug
        - OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
      script:
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j 4 && ctest --verbose

    - os: osx
      osx_image: xcode9.3
	  before_script:
		- export PATH=$PATH:/usr/local/opt/qt/bin
      before_install:
        - brew upgrade openssl boost cmake
        - brew install qt5
      env: 
        - BUILD_TYPE=Release
        - OPENSSL_ROOT_DIR="/usr/local/opt/openssl"
      script:
        - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then
            cmake . && make -j 4 && ctest --verbose;
          else
            echo Nothing to build...;
          fi
      after_success:
        - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then 
            chmod +x ./deploy.sh;
            ./deploy.sh;
          fi

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
            - libssl-dev
            - qtdeclarative5-dev
            - qtdeclarative5-qtquick2-plugin
      before_install:
        - eval "CC=gcc-7 && CXX=g++-7"
      env: BUILD_TYPE=Debug
      script:
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j 4 && ctest --verbose

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
            - libssl-dev
            - qtdeclarative5-dev
            - qtdeclarative5-qtquick2-plugin
      before_install:
        - eval "CC=gcc-7 && CXX=g++-7"
      env: BUILD_TYPE=Release
      script:
        - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then
            cmake . && make -j 4 && ctest --verbose;
          else
            echo Nothing to build...;
          fi
      after_success:
        - if [ $TRAVIS_EVENT_TYPE == "cron" ]; then 
            chmod +x ./deploy.sh;
            ./deploy.sh;
          fi

notifications:
  email:
    - big.romanov@gmail.com
