language: cpp

git:
  depth: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-all-dev
      - libssl-dev
      - curl
      - nvidia-cuda-toolkit
before_install:
  - export TZ=Etc/GMT-3
  - wget "https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh"
  - sudo sh cmake-3.12.0-Linux-x86_64.sh --skip-license --prefix=/usr
  - eval "CC=gcc-7 && CXX=g++-7"
env: BUILD_TYPE=Release OS_FOLDER=linux

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDEBUG_MESSAGES_IN_RELEASE_MODE=On -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=$TRAVIS_BRANCH -DBEAM_NO_QT_UI_WALLET=On -DBEAM_USE_GPU=On . && make beam-node -j4;

# TODO: version detection should be in one place
before_script:
  - BEAM_VERSION="1.0.$(git rev-list HEAD --count)"

after_success:
  # deploy using ftp server
  - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$BUILD_TYPE/$OS_FOLDER
  - tar -cvzf beam-node-gpu-$BEAM_VERSION.tar.gz --directory=$HOME/build/beam-mw/beam/beam beam-node beam-node.cfg
  - curl --retry 3 --ftp-create-dirs -T beam-node-gpu-$BEAM_VERSION.tar.gz $BUILDS_SERVER_PATH/

notifications:
  email:
    - big.romanov@gmail.com
