language: cpp

script:
  - cmake .
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
      before_install:
        - eval "brew update && brew cask uninstall --force oclint && brew install gcc@7 && CC=gcc-7 && CXX=g++-7 && brew install boost && brew install libuv"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
      before_install:
        - eval "CC=gcc-7 && CXX=g++-7"
