version: '{build}'
image: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  
configuration:
- Release

platform:
- x64

environment:
  matrix:
  - arch: Win64

# install: git submodule update --init --recursive

before_build:
  cmd: cmake -G "Visual Studio 15 2017 Win64"

build:
  project: c:\projects\beam\beam.sln
  verbosity: minimal
  parallel: true
