version: '{build}'
image: Visual Studio 2017

configuration:
- Release

platform:
- x64

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  OPENSSL_ROOT_DIR: c:\beam-libs\openssl
  QT5_ROOT_DIR: c:\beam-libs\qt5-static-win
  QML_IMPORT_PATH: c:\beam-libs\qt5-static-win\qml
  BUILD_SERVER:
    secure: l9RqB2YbSnNIKZqTwnd67BHAXvbjmpj9zcf+YQPi9zfzsVeSysaoLD7gy4gSMjWurk2JVHjRpviw4bBxUbu2sA==
  matrix:
  - arch: Win64

before_build:
  - cmd: git clone --depth=1 https://github.com/beam-mw/libs.git c:/beam-libs
  - cmd: git clone --depth=1 https://github.com/nesbox/qt5-static-win.git c:/beam-libs/qt5-static-win
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=%APPVEYOR_REPO_BRANCH%

test_script:
  - cmd: ctest -C Release --verbose

build:
  project: c:\projects\beam\beam.sln
  verbosity: minimal
  parallel: true

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-

    cpack --verbose -G NSIS

    git rev-list HEAD --count > BEAM_VERSION_REVISION

    set /p BEAM_VERSION_REVISION=<BEAM_VERSION_REVISION

    set BEAM_VERSION=1.0.%BEAM_VERSION_REVISION%

    7z a c:/projects/beam/beam/Release/beam-node-%BEAM_VERSION%.zip c:/projects/beam/beam/Release/beam-node.exe c:/projects/beam/beam/beam-node.cfg

    7z a c:/projects/beam/beam/Release/beam-wallet-cli-%BEAM_VERSION%.zip c:/projects/beam/wallet/Release/beam-wallet.exe c:/projects/beam/wallet/beam-wallet.cfg

    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/Release/beam-node-%BEAM_VERSION%.zip" %BUILDS_SERVER_PATH%/

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/Release/beam-wallet-cli-%BEAM_VERSION%.zip" %BUILDS_SERVER_PATH%/

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/BeamWallet-0.0.1-win64.exe" "%BUILDS_SERVER_PATH%/Beam-Wallet-%BEAM_VERSION%.exe"

notifications:
  - provider: Email
    to:
      - big.romanov@gmail.com
